[package]
name = "terracotta"
version = "0.1.2"
description = "Boilerplate webserver application based on Axum"
categories = ["asynchronous", "authentication", "rust-patterns", "web-programming", "web-programming::http-server"]
keywords = ["web", "server", "boilerplate", "example", "authentication"]
edition = "2021"
license = "MIT"
authors = ["Dan Williams <dan@dotfive.co.uk>"]
repository = "https://github.com/danwilliams/terracotta"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true     # Automatically strip symbols from the binary
opt-level = 3    # Maximum optimisation (this is the cargo default)
lto = "thin"     # Enable link-time optimisation (fast)

[dependencies]
axum = "0.6.18"
axum-sessions = "0.5.0"
base64 = "0.21.2"
bytes = "1.4.0"
figment = { version = "0.10.10", features = ["toml", "env"] }
include_dir = { version = "0.7.3", features = ["glob"] }
mime_guess = "2.0.4"
rand = { version = "0.8.5", features = ["min_const_gen"] }
ring = "0.16.20"
secrecy = "0.8.0"
serde = { version = "1.0.164", features = ["derive"] }
smart-default = "0.7.1"
tera = "1.19.0"
tokio = { version = "1.28.2", features = ["fs", "io-std", "io-util", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.8", features = ["io", "io-util"] }
tower-http = { version = "0.4.0", features = ["catch-panic", "trace"] }
tracing = "0.1.37"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
url = "2.4.0"
